[build]
    command = "yarn build"
    publish = "build"
    base = ""

[[redirects]]
  from = "/*"
  to = "/"

[[redirects]]
  from = "/api/*"
  to = "http://capstonesalonki.herokuapp.com/api/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
