[build]
    command = "yarn build"
    publish = "build"
    base = ""


[[redirects]]
  from = "/api/reading"
  to = "http://capstonesalonki.herokuapp.com/api/reading"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
